apiVersion: skaffold/v2beta18
kind: Config

profiles:
  - name: local
    build:
      local:
        push: true
      artifacts:
        - image: minsoo11/sample-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=local"           
            fromImage: eclipse-temurin:17.0.2_8-jre

